import '@testing-library/jest-dom/vitest';
import { vi } from 'vitest';
import { DEFAULT_PUBLIC_DISPLAY_SETTINGS } from '@shared/types';

Object.defineProperty(window, 'dndTracker', {
  configurable: true,
  value: {
    listCampaigns: vi.fn(),
    createCampaign: vi.fn(),
    deleteCampaign: vi.fn(),
    getCampaignDetail: vi.fn(),
    savePlayer: vi.fn(),
    deletePlayer: vi.fn(),
    importRuleholderCreature: vi.fn(),
    fetchRuleholderSpell: vi.fn(),
    saveCreature: vi.fn(),
    deleteCreature: vi.fn(),
    saveEncounter: vi.fn(),
    deleteEncounter: vi.fn(),
    saveEncounterGroup: vi.fn(),
    deleteEncounterGroup: vi.fn(),
    saveEncounterPlayerSetting: vi.fn(),
    saveEncounterLair: vi.fn(),
    deleteEncounterLair: vi.fn(),
    startCombat: vi.fn(),
    prepareCombat: vi.fn(),
    confirmCombatInitiative: vi.fn(),
    beginInitiativeExchange: vi.fn(),
    swapCombatInitiative: vi.fn(),
    cancelInitiativeExchange: vi.fn(),
    onCombatPreparation: vi.fn(() => () => undefined),
    cancelCombatPreparation: vi.fn(),
    addCombatantsToCombat: vi.fn(),
    getCombatSession: vi.fn(),
    updateCombatant: vi.fn(),
    reorderCombatants: vi.fn(),
    setActiveCombatant: vi.fn(),
    advanceTurn: vi.fn(),
    retreatTurn: vi.fn(),
    endRound: vi.fn(),
    advanceRound: vi.fn(),
    retreatRound: vi.fn(),
    completeCombat: vi.fn(),
    dismissCombatXpAward: vi.fn(),
    showPublicFeatureCard: vi.fn(),
    dismissPublicFeatureCard: vi.fn(),
    openPlayerWindow: vi.fn(),
    getPlayerView: vi.fn(),
    onPlayerView: vi.fn(() => () => undefined),
    getPublicDisplaySettings: vi.fn().mockResolvedValue(DEFAULT_PUBLIC_DISPLAY_SETTINGS),
    savePublicDisplaySettings: vi.fn().mockResolvedValue(DEFAULT_PUBLIC_DISPLAY_SETTINGS),
    getUpdateStatus: vi.fn(),
    checkForUpdates: vi.fn(),
    downloadUpdate: vi.fn(),
    installUpdate: vi.fn(),
    onUpdateStatus: vi.fn(() => () => undefined)
  }
});
